### ISSUE TITLE
Shutting down mysql, query size

### ISSUE THREAD

**Issue by Teleriann** [BenCodez/VotingPlugin#978] opened 2020-10-05 12:50 UTC
Hello,

I have one question about mysql query. When i stop my server, it takes about 20-30 seconds to turn off. But when iam using VotingPlugin, then there is that thing exactly this: "[18:41:32 INFO]: [VotingPlugin] Shutting down mysql, query size: 14887". This one thing extend server turning off time to 5mins +-. So just this query takes about 4 minutes to shut down.

Can i do something with this, so it wont take this much time? Because when i need fast restart, then this is issue, and players must wait on lobby for longer time.

Thanks for your help.

**Comment by Teleriann** [comment] 2020-10-05 15:12
There is is, thats insane https://pastebin.com/wGUSNvSq

**Comment by BenCodez** [comment] 2020-10-05 16:07
Wanna set debug level to EXTRA and send the full server log from start to
finish?

Edit: Also try the latest update.

**Comment by Teleriann** [comment] 2020-10-05 20:52
All right, i will update VP and let you know how it works.

**Comment by Teleriann** [comment] 2020-10-06 12:54
Hello so,

I have tested it today, and there are results: https://pastebin.com/bvD62gD7

Still same problem longer query = takes longer time to stop.

**Comment by BenCodez** [comment] 2020-10-06 14:09
With debug level set to Extra do you see anything regarding queries while
the server is running. Queries are suppose to process in the background,
almost seems as if it's not

**Comment by Teleriann** [comment] 2020-10-06 15:12
You can understand it better: https://pastebin.com/4Tn1YQ0N

EDIT: More info if needed: https://pastebin.com/Hu2yGpwE

**Comment by BenCodez** [comment] 2020-10-06 21:04
Could you send from server startup to shutdown?

**Comment by BenCodez** [comment] 2020-10-06 21:27
This also should reduce the number of queries a bit:
http://bencodez.com/job/VotingPlugin/

**Comment by Teleriann** [comment] 2020-10-07 18:37
All right i will try it, thanks, also why do you need full log, i can provide info you need but i cant send full log here (privacy of players etc...)

I hope you understand, i will try that new version and ill let you know if it is all right.

**Comment by BenCodez** [comment] 2020-10-07 18:44
Can you send the log just before shutting down?

**Comment by Teleriann** [comment] 2020-10-07 19:35
There it is: https://pastebin.com/YHEZQady

**Comment by Teleriann** [comment] 2020-10-07 21:20
Oh, i guess you need extra debug right?

**Comment by BenCodez** [comment] 2020-10-07 21:21
Yes, and redownload the latest build here as well
http://bencodez.com/job/VotingPlugin/

**Comment by Teleriann** [comment] 2020-10-09 16:57
i do not understand it, i have not downloaded new version of the plugin, i wanted to test it so i set debug to extra, and i turned off server, everything was all right no query....

**Comment by BenCodez** [comment] 2020-10-09 20:50
Interesting, that's what I would expect to see normally.

**Comment by Teleriann** [comment] 2020-10-09 22:10
Ok so there it is, this is from right now: https://pastebin.com/X76smn6L

**Comment by BenCodez** [comment] 2020-10-09 22:56
Thanks, I have an idea of what the issue is. The background task for mysql seems to have stopped. See what this build does:
http://bencodez.com/job/VotingPlugin/

**Comment by Teleriann** [comment] 2020-10-09 23:11
All right, i have uploaded it to server, i will put more info tomorrow.

**Comment by Teleriann** [comment] 2020-10-10 18:33
It works perfectly, thank you so much <3

**Comment by BenCodez** [comment] 2020-10-10 18:51
Do you see this in the log at all?

"MySQL background task not working, fixing"

**Comment by Teleriann** [comment] 2020-10-10 23:11
No, i do not

**Comment by BenCodez** [comment] 2020-10-10 23:13
Hmm, okay, good to know, gonna close this, reopen if the issue pops up.

**Closed as completed by BenCodez** 2020-10-10 23:13 UTC
Labels: Question/Concern
